-- ⚠️ TEMPORAL — SOLO PARA SMOKE TEST. BORRAR O REVERTIR EN CUANTO
-- EL LOGIN ESTÉ IMPLEMENTADO. NO DEJAR ESTO EN UN ENTORNO REAL.
CREATE POLICY "temp_test_anon_mesas" ON mesas
FOR SELECT TO anon USING (true);
